org: porservermevoy # copiar organizacion creada en serverless
service: api-cursos

provider:
  name: aws
  runtime: python3.13
  memorySize: 1024
  timeout: 20
  iam:
    role: arn:aws:iam::325577839626:role/LabRole  #el rol sale del servicio IAM LabRole

functions:
  listar:
    handler: ListarCursos.lambda_handler
    events: # estas secciones son las conexiones a api g
      - http:
          path: /cursos/listar
          method: get
          cors: true
          integration: lambda
  buscar:
    handler: BuscarCurso.lambda_handler
    events:
      - http:
          path: /cursos/buscar
          method: post
          cors: true
          integration: lambda
  crear:
    handler: CrearCurso.lambda_handler
    events:
      - http:
          path: /cursos/crear
          method: post
          cors: true
          integration: lambda
  modificar:
    handler: ModificarCurso.lambda_handler
    events:
      - http:
          path: /cursos/modificar
          method: put
          cors: true
          integration: lambda
  eliminar:
    handler: EliminarCurso.lambda_handler
    events:
      - http:
          path: /cursos/eliminar
          method: delete
          cors: true
          integration: lambda
